--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_lua-roact-policy-provider"]["lua-roact-policy-provider"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package